# Generated by Django 3.1 on 2020-08-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_category', '0003_auto_20200827_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
