# Generated by Django 3.1 on 2020-09-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_contact', '0004_auto_20200917_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
