# Generated by Django 3.1 on 2020-09-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('instagram', models.CharField(max_length=150)),
                ('telegram', models.CharField(max_length=150)),
                ('youtube', models.CharField(max_length=150)),
                ('github', models.CharField(max_length=150)),
                ('linkedin', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Personal Info',
                'verbose_name_plural': 'Personal Infos',
            },
        ),
    ]
