# Generated by Django 3.1 on 2020-09-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='github',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='linkedin',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='telegram',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='youtube',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
