# Generated by Django 3.1 on 2020-09-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_info', '0002_auto_20200903_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='instagram',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
