# Generated by Django 3.1 on 2020-09-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_info', '0003_auto_20200903_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
