# Generated by Django 3.1 on 2020-08-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_blog', '0003_auto_20200824_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
    ]
