# Generated by Django 3.1 on 2020-11-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_blog', '0009_auto_20201103_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
