# Generated by Django 3.1 on 2020-11-04 10:27

import ckeditor.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_blog', '0010_remove_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2020, 11, 4, 10, 27, 21, 558963, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
